### ISSUE TITLE
Error On Set Clothing

### ISSUE THREAD

**Issue by zhanif** [willi123yao/GrowtopiaServerCS#4]
Is there any fix that make we can see the clothes after OnSpawn on the world?
The current bug is the player's skin color still white like OnSetClothing is never work
Idk what's going on with the bugs

**Comment by cmdocmd** [comment]
ofc there is a fix

**Comment by zhanif** [comment]
> ofc there is a fix

Would you like to tell me, only just that please

**Comment by cmdocmd** [comment]
dm me in discord cmd#4804

**Comment by zhanif** [comment]
Ok fixed
