### ISSUE TITLE
requesting help C#

### ISSUE THREAD

**Issue by YourBoiBusy** [willi123yao/GrowtopiaServerCS#6]
If i want host my C# app with log in and register form in my vps when i put 127.0.0.1 as ip users will get error of tables things bcz they arent using localhost for making the log in or register how should i host it to my vps?
in my pc i use 127.0.0.1 and it work because i made tables and everything for it but i want host it to other users that didnt made tables. i dont want them make tables and these things
hope i get a good ideas
(i tried my vps ip it didnt work i checked ports)
![Login_Regsiter 5_20_2020 10_55_53 AM](https://user-images.githubusercontent.com/61913559/82436123-00f83c00-9a9e-11ea-838e-48e6dcb10e66.png)

**Comment by sayomaki** [comment]
This seems to be a MySQL error and should be due to a setup misconfiguration on your side. Do check your server setup again for the database.

Closing this issue as it is not related to the current code.
